$ROOT_DIR = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $ROOT_DIR

Write-Host "========================================"
Write-Host "  Update Example PDFs"
Write-Host "========================================"
Write-Host ""

# ---- Find xelatex ----
$texCmd = Get-Command "xelatex" -ErrorAction SilentlyContinue
if (-not $texCmd) {
    foreach ($p in @("D:\texlive\2024\bin\windows\xelatex.exe","C:\texlive\2024\bin\windows\xelatex.exe")) {
        if (Test-Path $p) { $texCmd = $p; $env:Path += ";$(Split-Path $p)"; break }
    }
    if (-not $texCmd) { Write-Host "Error: xelatex not found." -ForegroundColor Red; Read-Host; exit 1 }
}
Write-Host "Using: $texCmd"
Write-Host ""

$buildDir = "build"
$exampleDir = "example"
New-Item -ItemType Directory -Force -Path $buildDir | Out-Null

# ---- Helper: generate tex content ----
function Build-TexContent {
    param($SrcDir, $CourseName, $ShowSolutions)

    $files = Get-ChildItem -Path "$SrcDir/$CourseName" -Filter "*.tex" -File |
        Where-Object { -not $_.BaseName.StartsWith("_") -and -not $_.BaseName.StartsWith(".") } |
        Sort-Object { $_.BaseName }

    if ($files.Count -eq 0) { return $null }

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("% Auto-generated by update-example.ps1")
    [void]$sb.AppendLine('\documentclass[11pt,a4paper]{ctexart}')
    [void]$sb.AppendLine('\input{preamble.tex}')
    if ($ShowSolutions) { [void]$sb.AppendLine('\ShowSolutionstrue') }
    [void]$sb.AppendLine('\begin{document}')
    [void]$sb.AppendLine("\coursesection{$CourseName}")
    foreach ($f in $files) {
        [void]$sb.AppendLine("\subimport{$SrcDir/$CourseName/}{$($f.BaseName)}")
        [void]$sb.AppendLine('\clearpage')
    }
    [void]$sb.AppendLine('\end{document}')
    return $sb.ToString()
}

# ---- Helper: compile ----
function Run-Compile($TexContent, $OutputPdf) {
    $texFile = Join-Path $ROOT_DIR "__compile_temp.tex"
    Set-Content -Path $texFile -Value $TexContent -Encoding UTF8
    Remove-Item "$buildDir\__compile_temp.*" -ErrorAction SilentlyContinue
    $ok = $true
    foreach ($pass in 1..2) {
        & $texCmd -interaction=nonstopmode -output-directory="$buildDir" "__compile_temp.tex" *>$null 2>&1
        if (-not (Test-Path (Join-Path $buildDir "__compile_temp.pdf"))) { $ok = $false; break }
    }
    if (-not $ok) { return $false }
    $pdfFile = Join-Path $buildDir "__compile_temp.pdf"
    Move-Item $pdfFile $OutputPdf -Force
    Remove-Item "$buildDir\__compile_temp.*" -ErrorAction SilentlyContinue
    return $true
}

# ---- Compile all exam courses ----
Write-Host ">>> Compiling exams..." -ForegroundColor Cyan
$examDirs = Get-ChildItem -Directory "exam/*" | Sort-Object Name
$examSuccess = 0; $examFail = 0

foreach ($d in $examDirs) {
    $courseName = $d.Name
    Write-Host "  [$courseName]" -NoNewline

    # Questions only
    $texQ = Build-TexContent "exam" $courseName $false
    if (-not $texQ) { Write-Host "  (no tex files)"; continue }

    $pdfQ = Join-Path $buildDir "__exam_q_temp.pdf"
    if (Run-Compile $texQ $pdfQ) {
        $dest = Join-Path $exampleDir "${courseName}往年题-题目.pdf"
        Move-Item $pdfQ $dest -Force
        Write-Host " 题目" -NoNewline; Write-Host " OK" -ForegroundColor Green
        $examSuccess++
    } else {
        Write-Host " 题目" -NoNewline; Write-Host " FAILED" -ForegroundColor Red
        $examFail++
    }

    # Solutions
    $texS = Build-TexContent "exam" $courseName $true
    $pdfS = Join-Path $buildDir "__exam_s_temp.pdf"
    if (Run-Compile $texS $pdfS) {
        $dest = Join-Path $exampleDir "${courseName}往年题-解析.pdf"
        Move-Item $pdfS $dest -Force
        Write-Host "        解析" -NoNewline; Write-Host " OK" -ForegroundColor Green
        $examSuccess++
    } else {
        Write-Host "        解析" -NoNewline; Write-Host " FAILED" -ForegroundColor Red
        $examFail++
    }
}

Write-Host ""

# ---- Compile all homework courses ----
Write-Host ">>> Compiling homework..." -ForegroundColor Cyan
$hwDirs = Get-ChildItem -Directory "homework/*" | Sort-Object Name
$hwSuccess = 0; $hwFail = 0

foreach ($d in $hwDirs) {
    $courseName = $d.Name
    Write-Host "  [$courseName]" -NoNewline

    # Questions only
    $texQ = Build-TexContent "homework" $courseName $false
    if (-not $texQ) { Write-Host "  (no tex files)"; continue }

    $pdfQ = Join-Path $buildDir "__hw_q_temp.pdf"
    if (Run-Compile $texQ $pdfQ) {
        $dest = Join-Path $exampleDir "${courseName}作业题-题目.pdf"
        Move-Item $pdfQ $dest -Force
        Write-Host " 题目" -NoNewline; Write-Host " OK" -ForegroundColor Green
        $hwSuccess++
    } else {
        Write-Host " 题目" -NoNewline; Write-Host " FAILED" -ForegroundColor Red
        $hwFail++
    }

    # Solutions
    $texS = Build-TexContent "homework" $courseName $true
    $pdfS = Join-Path $buildDir "__hw_s_temp.pdf"
    if (Run-Compile $texS $pdfS) {
        $dest = Join-Path $exampleDir "${courseName}作业题-解析.pdf"
        Move-Item $pdfS $dest -Force
        Write-Host "        解析" -NoNewline; Write-Host " OK" -ForegroundColor Green
        $hwSuccess++
    } else {
        Write-Host "        解析" -NoNewline; Write-Host " FAILED" -ForegroundColor Red
        $hwFail++
    }
}

# ---- Summary ----
Write-Host ""
Write-Host "========================================"
Write-Host "  Done! Exam: $examSuccess OK, $examFail FAILED"
Write-Host "  Homework: $hwSuccess OK, $hwFail FAILED"
Write-Host "========================================"

Remove-Item (Join-Path $ROOT_DIR "__compile_temp.tex") -Force -ErrorAction SilentlyContinue
Read-Host "Press Enter to exit"
