#!/usr/bin/env bash
set -e

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

echo "========================================"
echo "  Update Example PDFs"
echo "========================================"
echo ""

# ---- Find xelatex ----
TEX_CMD=""
if command -v xelatex &>/dev/null; then
    TEX_CMD=$(command -v xelatex)
else
    for p in /Library/TeX/texbin/xelatex /usr/local/texlive/*/bin/*/xelatex /opt/homebrew/bin/xelatex; do
        [ -x "$p" ] && { TEX_CMD="$p"; break; }
    done
fi
if [ -z "$TEX_CMD" ]; then
    echo "Error: xelatex not found." >&2
    read -p "Press Enter to exit" _
    exit 1
fi
echo "Using: $TEX_CMD"
echo ""

build_dir="build"
example_dir="example"
mkdir -p "$build_dir"

# ---- Helper: compile a course ----
compile_course() {
    local src_dir="$1"      # exam or homework
    local course="$2"       # course folder name
    local category="$3"     # 往年题 or 作业题

    # Collect .tex files (skip hidden)
    local tex_files=()
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        b=$(basename "$f" .tex)
        [[ $b == _* || $b == .* ]] && continue
        tex_files+=("$b")
    done < <(
        for f in "$src_dir/$course/"*.tex; do
            [ -f "$f" ] && echo "$f"
        done | sort
    )
    [ ${#tex_files[@]} -eq 0 ] && return 1

    for sol in 0 1; do
        [ "$sol" -eq 0 ] && label="题目" || label="解析"
        printf "  [%s] %s ... " "$course" "$label"

        # Generate temp tex
        {
            printf '%% Auto-generated by update-example.sh\n'
            printf '\\documentclass[11pt,a4paper]{ctexart}\n'
            printf '\\input{preamble.tex}\n'
            [ "$sol" -eq 1 ] && printf '\\ShowSolutionstrue\n'
            printf '\\begin{document}\n'
            printf '\\coursesection{%s}\n' "$course"
            for fn in "${tex_files[@]}"; do
                printf '\\subimport{%s/%s/}{%s}\n' "$src_dir" "$course" "$fn"
                printf '\\clearpage\n'
            done
            printf '\\end{document}\n'
        } > "$ROOT_DIR/__compile_temp.tex"

        # Compile twice
        rm -f "$build_dir/__compile_temp."*
        "$TEX_CMD" -interaction=nonstopmode -output-directory="$build_dir" "__compile_temp.tex" >/dev/null 2>&1
        "$TEX_CMD" -interaction=nonstopmode -output-directory="$build_dir" "__compile_temp.tex" >/dev/null 2>&1

        if [ -f "$build_dir/__compile_temp.pdf" ]; then
            mv "$build_dir/__compile_temp.pdf" "$example_dir/${course}${category}-${label}.pdf"
            rm -f "$build_dir/__compile_temp."*
            printf "OK\n"
        else
            printf "FAILED\n"
            rm -f "$build_dir/__compile_temp."*
        fi
    done
}

# ---- Compile exam courses ----
echo ">>> Compiling exams..."
exam_ok=0; exam_fail=0
for d in exam/*/; do
    [ -d "$d" ] || continue
    course=$(basename "$d")
    compile_course "exam" "$course" "往年题" && exam_ok=$((exam_ok+1)) || exam_fail=$((exam_fail+1))
done

echo ""

# ---- Compile homework courses ----
echo ">>> Compiling homework..."
hw_ok=0; hw_fail=0
for d in homework/*/; do
    [ -d "$d" ] || continue
    course=$(basename "$d")
    compile_course "homework" "$course" "作业题" && hw_ok=$((hw_ok+1)) || hw_fail=$((hw_fail+1))
done

# ---- Summary ----
echo ""
echo "========================================"
echo "  Done! Exam: $exam_ok OK, $exam_fail FAILED"
echo "  Homework: $hw_ok OK, $hw_fail FAILED"
echo "========================================"

rm -f "$ROOT_DIR/__compile_temp.tex" 2>/dev/null
read -p "Press Enter to exit" _
