#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR" || exit 1

# ---- Find xelatex ----
TEX_CMD=""
if command -v xelatex &>/dev/null; then
    TEX_CMD=$(command -v xelatex)
else
    for p in /Library/TeX/texbin/xelatex /usr/local/texlive/*/bin/*/xelatex /opt/homebrew/bin/xelatex; do
        [ -x "$p" ] && { TEX_CMD="$p"; break; }
    done
fi
if [ -z "$TEX_CMD" ]; then
    echo "错误：未找到 xelatex。" >&2
    read -p "按 Enter 退出" _
    exit 1
fi

# ---- Helper ----
read_default() {
    local p="$1" d="$2" r
    read -p "$p" r
    echo "${r:-$d}"
}

# ---- Mode ----
mode=$(read_default "编译类型 [E/H, Enter=E]: " "E")
is_exam=0
[ "$mode" = "E" ] || [ "$mode" = "e" ] && is_exam=1
src_dir=$([ "$is_exam" -eq 1 ] && echo "exam" || echo "homework")

s=$(read_default "答案模式 [a/b/c, Enter=c]: " "c")
both=0; show_sol=0
[ "$s" = "c" ] && { both=1; show_sol=1; }
[ "$s" = "b" ] && show_sol=1

# ---- Scan courses ----
courses=()
if [ ! -d "$src_dir" ]; then
    echo "错误：目录 $src_dir 不存在。" >&2
    read -p "按 Enter 退出" _; exit 1
fi

sort_pattern='^第([0-9]+)次作业$'
for d in "$src_dir"/*/; do
    [ -d "$d" ] || continue
    cname=$(basename "$d")
    items=()
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        items+=("$f")
    done < <(
        for f in "$d"*.tex; do
            [ -f "$f" ] || continue
            b=$(basename "$f" .tex)
            [[ $b == _* || $b == .* ]] && continue
            if [[ $b =~ $sort_pattern ]]; then
                printf "%05d_%s\n" "${BASH_REMATCH[1]}" "$b"
            else
                echo "$b"
            fi
        done | sort | sed 's/^[0-9]*_//'
    )
    [ ${#items[@]} -eq 0 ] && continue
    entry="$cname"
    for item in "${items[@]}"; do entry+=$'\x1F'"$item"; done
    courses+=("$entry")
done

if [ ${#courses[@]} -eq 0 ]; then
    echo "错误：未找到课程内容。" >&2
    read -p "按 Enter 退出" _; exit 1
fi

# ---- Menu ----
for i in "${!courses[@]}"; do
    IFS=$'\x1F' read -ra parts <<< "${courses[$i]}"
    printf "  %d. %s\n" $((i+1)) "${parts[0]}"
    for ((j=1; j<${#parts[@]}; j++)); do
        printf "      %d.%d %s\n" $((i+1)) "$j" "${parts[$j]}"
    done
done

# ---- Selection ----
out_dir="build"; mkdir -p "$out_dir"
selected_items=()
while true; do
    read -p "内容编号 (如 5 或 4,5.2): " selection
    [ -z "$selection" ] && { printf "输入有误，请重新输入。\n"; continue; }
    IFS=',' read -ra parts <<< "$selection"
    selected_items=(); valid=1
    for part in "${parts[@]}"; do
        part=$(echo "$part" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        if [[ $part =~ ^([0-9]+)\.([0-9]+)$ ]]; then
            c=${BASH_REMATCH[1]}; i=${BASH_REMATCH[2]}
            if [ "$c" -ge 1 ] && [ "$c" -le "${#courses[@]}" ]; then
                IFS=$'\x1F' read -ra cp <<< "${courses[$((c-1))]}"
                if [ "$i" -ge 1 ] && [ "$i" -lt "${#cp[@]}" ]; then
                    selected_items+=("$c.$i")
                else valid=0; break; fi
            else valid=0; break; fi
        elif [[ $part =~ ^[0-9]+$ ]]; then
            c=$part
            [ "$c" -ge 1 ] && [ "$c" -le "${#courses[@]}" ] && selected_items+=("$c.*") || { valid=0; break; }
        else valid=0; break; fi
    done
    [ "$valid" -eq 1 ] && [ ${#selected_items[@]} -gt 0 ] && break
    printf "输入有误，请重新输入。\n"
done

gen_toc=$(read_default "生成目录 [y/n, Enter=n]: " "n")
out_name=$(read_default "输出文件名 [Enter=compiled]: " "compiled")

# ---- Generate TeX ----
# Note: use "\\foo" (double-quoted with shell-escaped backslash)
# to avoid printf interpreting escapes like \u, \n in LaTeX strings.
generate_tex() {
    local show_sol="$1" outfile="$2"
    {
        printf '%% Auto-generated by compile.sh %s\n' "$(date)"
        printf '%s\n' "\\documentclass[11pt,a4paper]{ctexart}"
        printf '%s\n' "\\input{preamble.tex}"
        [ "$show_sol" -eq 1 ] && printf '%s\n' "\\ShowSolutionstrue"
        printf '%s\n' "\\begin{document}"
        if [ "$gen_toc" = "y" ] || [ "$gen_toc" = "Y" ]; then
            printf '%s\n' "\\tableofcontents"
            printf '%s\n' "\\clearpage"
        fi
        for ((ci=0; ci<${#courses[@]}; ci++)); do
            cidx=$((ci+1))
            found=0
            for sel in "${selected_items[@]}"; do
                [ "$sel" = "$cidx.*" ] && { found=1; break; }
                [[ $sel == "$cidx."* ]] && { found=1; break; }
            done
            [ "$found" -eq 0 ] && continue
            IFS=$'\x1F' read -ra cp <<< "${courses[$ci]}"
            printf '%s\n' "\\coursesection{${cp[0]}}"
            all_sel=0
            for sel in "${selected_items[@]}"; do
                [ "$sel" = "$cidx.*" ] && { all_sel=1; break; }
            done
            for ((ji=1; ji<${#cp[@]}; ji++)); do
                if [ "$all_sel" -eq 1 ] || [[ " ${selected_items[*]} " == *" $cidx.$ji "* ]]; then
                    printf '%s\n' "\\subimport{${src_dir}/${cp[0]}/}{${cp[$ji]}}"
                    printf '%s\n' "\\clearpage"
                fi
            done
        done
        printf '%s\n' "\\end{document}"
    } > "$outfile"
}

# ---- Compile ----
run_compile() {
    local tex_file="$1" output_pdf="$2"
    cp "$tex_file" "$ROOT_DIR/__compile_temp.tex"
    rm -f "$out_dir/__compile_temp."*
    "$TEX_CMD" -interaction=nonstopmode -output-directory="$out_dir" "__compile_temp.tex" >/dev/null 2>&1
    "$TEX_CMD" -interaction=nonstopmode -output-directory="$out_dir" "__compile_temp.tex" >/dev/null 2>&1
    if [ -f "$out_dir/__compile_temp.pdf" ]; then
        mv "$out_dir/__compile_temp.pdf" "$output_pdf"
        rm -f "$out_dir/__compile_temp."*
        return 0
    fi
    return 1
}

# ---- Main ----
outputs=(); main_saved=0

if [ "$both" -eq 1 ]; then
    for sol in 0 1; do
        [ "$sol" -eq 0 ] && lbl="题目版" || lbl="解析版"
        [ "$sol" -eq 0 ] && sfx="-题目" || sfx="-解析"
        printf "编译%s... " "$lbl"
        generate_tex "$sol" "$ROOT_DIR/__compile_current.tex"
        pdf="$out_dir/$out_name$sfx.pdf"
        if run_compile "$ROOT_DIR/__compile_current.tex" "$pdf"; then
            printf "OK\n"; outputs+=("$pdf")
        else
            printf "失败\n"
        fi
        [ "$main_saved" -eq 0 ] && cp "$ROOT_DIR/__compile_current.tex" "$ROOT_DIR/main.tex" && main_saved=1
    done
else
    [ "$show_sol" -eq 1 ] && lbl="解析版" || lbl="题目版"
    printf "编译%s... " "$lbl"
    generate_tex "$show_sol" "$ROOT_DIR/__compile_current.tex"
    pdf="$out_dir/$out_name.pdf"
    if run_compile "$ROOT_DIR/__compile_current.tex" "$pdf"; then
        printf "OK\n"; outputs+=("$pdf")
    else
        printf "失败\n"
    fi
    cp "$ROOT_DIR/__compile_current.tex" "$ROOT_DIR/main.tex"
fi

rm -f "$ROOT_DIR/__compile_temp.tex" "$ROOT_DIR/__compile_current.tex" 2>/dev/null

if [ ${#outputs[@]} -gt 0 ]; then
    printf "\n编译成功！\n"
    for f in "${outputs[@]}"; do
        echo "  $f"
        open "$f" 2>/dev/null || true
    done
else
    printf "编译出错。\n" >&2
    [ -f "$out_dir/__compile_temp.log" ] && grep "^!" "$out_dir/__compile_temp.log" 2>/dev/null | head -20
fi

read -t 5 -p "按 Enter 退出（5秒后自动退出）..." _ 2>/dev/null || true
