$ROOT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ROOT_DIR

$texCmd = Get-Command "xelatex" -ErrorAction SilentlyContinue
if (-not $texCmd) {
    foreach ($p in @("D:\texlive\2024\bin\windows\xelatex.exe","C:\texlive\2024\bin\windows\xelatex.exe")) {
        if (Test-Path $p) { $texCmd = $p; $env:Path += ";$(Split-Path $p)"; break }
    }
    if (-not $texCmd) { Write-Host "Error: xelatex not found." -ForegroundColor Red; Read-Host; exit 1 }
}

function Read-Default($Prompt, $Default) {
    $v = Read-Host $Prompt
    if ([string]::IsNullOrWhiteSpace($v)) { return $Default }
    return $v.Trim()
}

function Get-NaturalSortKey($Name) {
    return [regex]::Replace($Name, '\d+', {
        param($m)
        $m.Value.PadLeft(10, '0')
    })
}

$mode = Read-Default "Mode [E/H, Enter=E]" "E"
$isExam = $mode -eq "E" -or $mode -eq "e"
$srcDir = if ($isExam) { "exam" } else { "homework" }

$s = Read-Default "Answer mode [a/b/c, Enter=c]" "c"
$both = $s -eq "c"
$showSol = $s -eq "b" -or $both

$courses = @()
$dirs = Get-ChildItem -Directory "$srcDir\*" | Sort-Object { Get-NaturalSortKey $_.Name }
if ($dirs.Count -eq 0) { Write-Host "No course directories found." -ForegroundColor Red; Read-Host; exit 1 }

foreach ($d in $dirs) {
    $items = @(); $displays = @()
    foreach ($f in Get-ChildItem -Path $d.FullName -Filter "*.tex" -File | Sort-Object { Get-NaturalSortKey $_.BaseName }) {
        $fname = $f.BaseName
        if ($fname.StartsWith("_") -or $fname.StartsWith(".")) { continue }
        $items += $fname; $displays += $fname
    }
    $courses += [PSCustomObject]@{ Name = $d.Name; Items = $items; Displays = $displays; Src = $d.FullName }
}

for ($i = 0; $i -lt $courses.Count; $i++) {
    Write-Host "  $($i+1). $($courses[$i].Name)"
    for ($j = 0; $j -lt $courses[$i].Items.Count; $j++) {
        Write-Host "      $($i+1).$($j+1) $($courses[$i].Displays[$j])"
    }
}

$outDir = "build"; New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$selection = ""
while ($true) {
    $selection = Read-Host "Selection (e.g. 5 or 4,5.2)"
    if ([string]::IsNullOrWhiteSpace($selection)) { Write-Host "Invalid input, try again."; continue }
    $selected = @()
    foreach ($part in $selection.Split(',')) { $part = $part.Trim()
        if ($part -match '^(\d+)\.(\d+)$') { $c=[int]$matches[1]; $i=[int]$matches[2]
            if ($c-ge1 -and $c-le$courses.Count -and $i-ge1 -and $i-le$courses[$c-1].Items.Count) { $selected+="$c.$i" } }
        elseif ($part -match '^\d+$') { $c=[int]$part
            if ($c-ge1 -and $c-le$courses.Count) { $selected+="$c.*" } }
    }
    if ($selected.Count -gt 0) { break }
    Write-Host "Invalid input, try again."
}

$genToc = Read-Default "Table of contents [y/n, Enter=n]" "n"
$outName = Read-Host "Output filename [Enter=compiled]"
if ([string]::IsNullOrWhiteSpace($outName)) { $outName = "compiled" }

function Build-TexContent($ShowSolutions) {
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("% Auto-generated by compile.ps1 $(Get-Date)")
    [void]$sb.AppendLine('\documentclass[11pt,a4paper]{ctexart}')
    [void]$sb.AppendLine('\input{preamble.tex}')
    if ($ShowSolutions) { [void]$sb.AppendLine('\ShowSolutionstrue') }
    [void]$sb.AppendLine('\begin{document}')
    if ($genToc -match "^[yY]") { [void]$sb.AppendLine('\tableofcontents\clearpage') }
    for ($ci=0; $ci -lt $courses.Count; $ci++) {
        $cidx = $ci+1
        if (-not ($selected | Where-Object { $_ -eq "$cidx.*" -or $_ -like "$cidx.*" })) { continue }
        [void]$sb.AppendLine("\coursesection{$($courses[$ci].Name)}")
        $allSel = $selected -contains "$cidx.*"
        for ($ji=0; $ji -lt $courses[$ci].Items.Count; $ji++) {
            $jidx = $ji+1
            if ($allSel -or ($selected -contains "$cidx.$jidx")) {
                [void]$sb.AppendLine("\subimport{$srcDir/$($courses[$ci].Name)/}{$($courses[$ci].Items[$ji])}")
                [void]$sb.AppendLine('\clearpage')
            }
        }
    }
    [void]$sb.AppendLine('\end{document}')
    return $sb.ToString()
}

function Run-Compile($TexContent, $OutputPdf) {
    $texFile = Join-Path $ROOT_DIR "__compile_temp.tex"
    Set-Content -Path $texFile -Value $TexContent -Encoding UTF8
    Remove-Item "$outDir\__compile_temp.*","$outDir\*.log","$outDir\*.aux","$outDir\*.out","$outDir\*.toc" -ErrorAction SilentlyContinue
    & $texCmd -interaction=nonstopmode -output-directory="$outDir" "__compile_temp.tex" *>$null 2>&1
    & $texCmd -interaction=nonstopmode -output-directory="$outDir" "__compile_temp.tex" *>$null 2>&1
    $pdfFile = Join-Path $outDir "__compile_temp.pdf"
    if (-not (Test-Path $pdfFile)) { return $false }
    Move-Item $pdfFile $OutputPdf -Force
    Remove-Item "$outDir\__compile_temp.*","$outDir\*.log","$outDir\*.aux","$outDir\*.out","$outDir\*.toc" -ErrorAction SilentlyContinue
    return $true
}

$outputs = @(); $mainTex = $null
$jobs = if ($both) { @(@{Sol=$false;Label="questions";Sfx="-questions"},@{Sol=$true;Label="solutions";Sfx="-solutions"}) }
         else { @(@{Sol=$showSol;Label=if($showSol){"solutions"}else{"questions"};Sfx=""}) }

foreach ($job in $jobs) {
    Write-Host "Compiling $($job.Label)..." -NoNewline
    $tex = Build-TexContent $job.Sol
    $pdf = Join-Path $outDir "$outName$($job.Sfx).pdf"
    if (Run-Compile $tex $pdf) { Write-Host " OK" -ForegroundColor Green; $outputs += $pdf }
    else { Write-Host " FAILED" -ForegroundColor Red }
    if (-not $mainTex) { $mainTex = $tex }
}
Set-Content -Path (Join-Path $ROOT_DIR "main.tex") -Value $mainTex -Encoding UTF8

Remove-Item (Join-Path $ROOT_DIR "__compile_temp.tex") -Force -ErrorAction SilentlyContinue

if ($outputs.Count -gt 0) { Write-Host "Compilation successful!" -ForegroundColor Green; $outputs | ForEach-Object { Write-Host "  $_"; Start-Process $_ } }
else { Write-Host "Compilation failed." -ForegroundColor Red }

Write-Host "Press Enter to exit..." -NoNewline
try { $cnt=5; while ($cnt -gt 0 -and -not [Console]::KeyAvailable) { Start-Sleep -Seconds 1; $cnt-- }; if ([Console]::KeyAvailable) { [Console]::ReadKey($true) | Out-Null } } catch { Start-Sleep -Seconds 5 }
